### ISSUE TITLE
Move filters creation inside tasks in README

### ISSUE THREAD

**Issue by hoho** [sindresorhus/gulp-filter#15]
Examples in README tell to create filters outside actual tasks. And it works on the first run, but on the second run (when you rerun task with gulp.watch) it throws `write after end` exception. It took me some time to realize that my plugin isn't the one who caused the problem.

In conclusion, I guess everything like `var jsFilter = gulpFilter('**/*.js');` should be moved inside task functions in README examples.

**Comment by Disorrder** [comment]
same trouble. Any solutions?

**Comment by tim93422** [comment]
I just got bit by this today. Could we document this in the README somewhere?

**Comment by mattppp** [comment]
Same here. Not only should it be in the task file, it should be directly in the scope it's used in. Ran into this problem when running a forEach/map in a gulp task.

**Comment by hoho** [comment]
Guys, it's the beautiful world of open source — you can fix and pull request anything :).
I have fixed README a while ago, perhaps it's disappeared during the project's evolution (I didn't check it since then). Yet nobody stops you from fixing it again.
