### ISSUE TITLE
Is passing File.relative to multimatch correct?

### ISSUE THREAD

**Issue by joedyndale** [sindresorhus/gulp-filter#20]
Hi,

It seems to me that as it is, the example on the home page of this module won't work, as it is similar to an issue I had which I've described here: http://stackoverflow.com/questions/24687468/gulp-filter-filters-out-all-files/24708315#24708315

In any case, I'm wondering if it wouldn't be better to pass File.path to the multimatch function instead? When passing File.relative, as is done now, only the filename is passed, which makes it impossible to use filter patterns that filter based on a directory name. An even better approach might be to pass File.path minus File.cwd (leaving the relative path in relation to the gulpfile). It's 2:30 A.M, so I admit I haven't spent a lot of time thinking this through, but thought I'd make the suggestion. I could make a pull request, but I'm not sure whether this is something that's desired by other people as well ;)

**Comment by david-gang** [comment]
Hi,

Shouldn't it be documented that the file.relative is used?
I don't see it in any place in the docs  at https://github.com/sindresorhus/gulp-filter


Thanks,
David
