### ISSUE TITLE
2.0.1 restore() faulty

### ISSUE THREAD

**Issue by hans-d** [sindresorhus/gulp-filter#36]
`filter.restore()` is not working properly, where it does with 2.0.0
files passing `filter` are gone after `filter.restore()`

**Comment by nfroidure** [comment]
probably a regression introduced by my last fix https://github.com/sindresorhus/gulp-filter/issues/29

i'll try to make a test to reproduce this behavior, in order to help me, could you paste here the involved code?

**Comment by nfroidure** [comment]
This test should not work according to the reported issue https://github.com/sindresorhus/gulp-filter/blob/master/test.js#L129

Need more input to fix it.

**Comment by hans-d** [comment]
will see if I can make a standalone example in js.
Currently seeing the behaviour in my coffee-script based buildfile.
```
# quick example
gulp taks 'me', () ->
  filter = plugin.filter '**/*.js'
  gulp.src whatever
    .pipe filter                # 1
    .pipe plugin.actionX()      # 2
    .pipe filter.restore()      # 3
```
on `#1` a `.js` files comes through, processed at `#2` but disapperearing at `#3`.
Verified manually using `gulp-filelog`

**Comment by hans-d** [comment]
ah... I see in in the failing task i'm not using `gulp.src` but `gulp-watch`, so the stream is not flushed as it keeps watching for new files. (will update the example)

**Comment by nfroidure** [comment]
I see. So it is not a bug but a feature ;). It is your responsibility to end your stream pipeline.

**Comment by hans-d** [comment]
using gulp-watch the stream should not end.
And prior to 2.0.1 it works ok.

**Comment by nfroidure** [comment]
I think i got it. We should use something else than streamqueue that merges streams instead of queuing them here https://github.com/sindresorhus/gulp-filter/blob/master/index.js#L48

**Comment by hans-d** [comment]
Also, files that are filtered (so not available at `#2`) are directly available after `#3`, so the sequence of files is altered as well with 2.0.1

**Comment by nfroidure** [comment]
Ok, could write a test to reproduce the problem and added a fix https://github.com/sindresorhus/gulp-filter/pull/37

@sindresorhus need review ;)

**Comment by hans-d** [comment]
Thnx

**Comment by nfroidure** [comment]
@hans-d could you clone the repo and link it to your project to see if the issue is fully solved ?
