### ISSUE TITLE
Can't filter based on folder name

### ISSUE THREAD

**Issue by bbatha** [sindresorhus/gulp-filter#38]
Prior to upgrading to 2.0.2 (from 0.3.0) I was able to filter like so:

```javascript
gulp.src('./**')
       .pipe(gulpFilter('**/fonts/*')
       .pipe(doStuff());
```

Once I upgraded that filter no longer returns data. I believe  this behavior is an unintended consequence of df53fe36e295787c5f174a6cf0aea3e58a37c133 which compares the glob to the relative path of the file rather than the full path as expected. Is there a way to filter as specified in the example in gulp-filter 2.0?

**Comment by RyanMelenaNoesis** [comment]
I'm experiencing the same issue.  Was resolved by reverting to 2.0.1.

**Comment by RyanMelenaNoesis** [comment]
I think my issue (and perhaps yours) stem from the issue described here: https://github.com/sindresorhus/gulp-filter/issues/20

**Comment by kevva** [comment]
This worked fine for me:

```js
var gulp = require('gulp');
var gulpFilter = require('gulp-filter');

gulp.task('default', function () {
    gulp.src('**/*')
        .pipe(gulpFilter('**/abcabc/*'));
});
```
