### ISSUE TITLE
Can't create patterns that work both on Windows and Linux, because of path separator "\\"

### ISSUE THREAD

**Issue by duzun** [sindresorhus/gulp-filter#40]
I've spent some time trying to make `gulp-filter` work with a vary basic setup.
I discovered it is not doing what it is supposed to because I'm on a Windows machine and using "/" in paterns.

My solution was to use a function pattern like this one:

```javascript
gulpFilter(function (o) {
    var rel = o.relative.replace(/\\/g, '/');
    return pattern.test(rel);
});
```
instead of 
```javascript
gulpFilter(pattern);
```
and suddenly it worked.

I think it should be done internally by gulp-filter and let people write cross-platform gulp tasks easily.

**Comment by kevva** [comment]
Try setting `nonull: true` in the options.

**Comment by duzun** [comment]
Is `nonull` option documented anywhere?

**Comment by kevva** [comment]
Well, this module it using `multimatch` which uses `minimatch`. But there's a note here https://github.com/sindresorhus/gulp-filter#options.

**Comment by duzun** [comment]
I've read https://github.com/isaacs/minimatch#nonull and don't see how it solves the issue. 
From what I understand it would just help with debugging.

**Comment by kevva** [comment]
> If an escaped pattern has no matches, and the nonull flag is set, then minimatch.match returns the pattern as-provided, rather than interpreting the character escapes. For example, minimatch.match([], "\\*a\\?") will return "\\*a\\?" rather than "*a?". This is akin to setting the nullglob option in bash, except that it does not resolve escaped pattern characters.

**Comment by duzun** [comment]
`nonull: true` doesn't help in my case. It just doesn't filter according to my patters.
My pattern looks like this:

```javascript
gulpFilter(['*', '!js/file.js', '!js/files2.js'], { nonull: true });
```

As a result, `file.js` and `file2.js` get copied to the destination.
