### ISSUE TITLE
Using multiple outputs with filters

### ISSUE THREAD

**Issue by erquhart** [sindresorhus/gulp-filter#41]
For example, I'd like to put all files through certain pipes, but output some of the files to one destination, and others to a separate destination. Possible?

Here's what I'm currently using for a bump task:
```
var rootFilter = gulpFilter('!./src');
var srcFilter = gulpFilter('./src');
gulp.src(['package.json', 'bower.json', 'src/manifest.json'])
  .pipe(bump({type: 'patch'}))
  .pipe(srcFilter)
  .pipe(gulp.dest('./src'))
  .pipe(srcFilter.restore())
  .pipe(rootFilter)
  .pipe(gulp.dest('./'));
});
```

**Comment by kevva** [comment]
What's the problem? `rootFilter` should probably look like this `var rootFilter = gulpFilter(['*', '!./src']);`.

**Comment by erquhart** [comment]
I did try that, actually. I even tried filters that only grab one file, just to zero in on the issue:
```
  var bowerFilter = gulpFilter('bower.json');
  var manifestFilter = gulpFilter('src/manifest.json');
  gulp.src(['package.json', 'bower.json', 'src/manifest.json'])
    .pipe(bump({type: 'patch'}))
    .pipe(manifestFilter)
    .pipe(gulp.dest('./'))
    .pipe(manifestFilter.restore())
    .pipe(bowerFilter)
    .pipe(gulp.dest('./'));
```

**Comment by erquhart** [comment]
The above updates all files in memory, but only outputs the bower file.

**Comment by erquhart** [comment]
Also, I realize I'm outputting to the same destination twice - that's just to rule out a dest globbing error.

**Comment by kevva** [comment]
You could just do this if you don't really need to use `gulp-filter`:

```js
gulp.src(['package.json', 'bower.json', 'src/manifest.json'], {base: './'})
    .pipe(gulpBump())
    .pipe(gulp.dest('./'));
```

**Comment by erquhart** [comment]
But I actually do need to use gulp filter - the above is just a test. The issue is outputting to different destinations.

**Comment by kevva** [comment]
Well, can't you apply the same logic? If you aren't altering your directory structure you won't really need to output to multiple destinations.

**Comment by erquhart** [comment]
Ah - okay, I understand now. But future reference, does gulp-filter support outputting to multiple destinations or no?

**Comment by kevva** [comment]
Yes, if your paths match correctly. When you're using `gulp.src(['src/manifest.json'])` the `file.path` will only be `manifest.json` without the `src` prepended. You have to use the `base` option along with `gulp.src` for it to work.

**Comment by erquhart** [comment]
Understood. Thanks for entertaining my novice misunderstanding of globbing - much appreciated.
