### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by iaakash** [sindresorhus/gulp-filter#42]
gulp.task('build', ['inject', 'images', 'fonts'], function(){
    log('*** Building Production - Optimizing Assets - HTML,CSS,JS ***');

    var templateCache = config.temp + config.templateCache.file;
    var assets = $.useref.assets({ searchPath: './' });
    var cssFilter = $.filter('**/*.css');
    //var jsFilter = $.ignore.include('/*.js');

    return gulp
        .src(config.index)
        .pipe($.plumber())
        .pipe($.inject(gulp.src(templateCache, {read: false}),{
            starttag: ''
        }))
        .pipe(assets)
        //.pipe(cssFilter)
        //.pipe($.csso())
        //.pipe(cssFilter.restore())
        .pipe(jsFilter)
        .pipe($.uglify())
        .pipe(jsFilter.restore())
        .pipe(assets.restore())
        .pipe($.useref())
        .pipe(gulp.dest(config.build))
});

**Comment by kevva** [comment]
Well, this isn't a problem tied to this module. It's a problem somewhere in your code. Make sure that all modules are loaded and that you doesn't try to call a method/function that doesn't exist.

**Comment by msallati** [comment]
Change 
var cssFilter = $.filter('**/*.css');
to 
var cssFilter = $.filter('**/*.css', {restore: true});

**Comment by verona-rupes** [comment]
Thanks man that helped !!
