### ISSUE TITLE
Grab minified files

### ISSUE THREAD

**Issue by jrock2004** [sindresorhus/gulp-filter#47]
Using gulp filter with main-bower-files. I want to grab the minified files. Is this possible? I tried

    var jsFilter  = gulpFilter('*.min.js', {restore: true});

    return gulp.src(bowerMain())                                                    │
      .pipe(jsFilter)                                                              
      .pipe(gulp.dest('./temp/js'))
      .pipe(jsFilter.restore)

When I run it nothing gets copied. If I change filter to *.js it pulls all except minified files

**Comment by sindresorhus** [comment]
The pattern should be a relative path, not a filename. You could set the [`matchBase`](https://github.com/isaacs/minimatch#matchbase) option if you want the above behaviour.

Support questions are better asked on StackOverflow.
