### ISSUE TITLE
Glob isn't matching any files.

### ISSUE THREAD

**Issue by matracey** [sindresorhus/gulp-filter#48]
Maybe this is a problem with my understanding of how multimatch is matching by globs, but for some reason I can't get this snippet to work.

I'm using the `gulp-load-plugins` plugin, which is assigned to the variable `$`, in case you're wondering. I've tried directly requiring gulp-filter too.

    gulp.task("default", function() {
        var jsFilter = $.filter("**/*.js", {restore: true});
        var cssFilter = $.filter("**/*.css", {restore: true});
        var assets;

        return gulp.src("**/_Layout.cshtml")
            .pipe($.rename("_Layout.build.cshtml"))
            // gulp-useref: concatenates scripts/styles found within build tags in the Layout page.
            .pipe(assets = $.useref.assets({ searchPath: [config.wwwroot] }))
            // This filter will match nothing.
            .pipe(cssFilter)
            // No files in the pipe, so this won't run.
            .pipe($.csso())
            // Restores everything back.
            .pipe(cssFilter.restore)
            // Same again - matches nothing.
            .pipe(jsFilter)
            // Doesn't run.
            .pipe($.uglify())
            // Restores everything back.
            .pipe(jsFilter.restore)
            .pipe(assets.restore())
            .pipe($.useref())
            .pipe($.replace("../../wwwroot", ""))
            .pipe(gulp.dest("./tmp/"));
    });

The relative paths to the files in my stream are as follows:

1. `..\..\wwwroot\css\app.css`
2. `..\..\wwwroot\js\app.js`
3. `..\..\wwwroot\css\lib.css`
4. `..\..\wwwroot\js\lib.js`

The filters work fine if the relative path to the file doesn't have `..\..\wwwroot\css\` in it.

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gulp
Paste in the link to the question here so others can follow ;)
