### ISSUE TITLE
How to use with Yeoman Transform Stream

### ISSUE THREAD

**Issue by trevordmiller** [sindresorhus/gulp-filter#49]
From the ["Transform output files through streams" section of the Yeoman docs](http://yeoman.io/authoring/file-system.html), it says:

> "Note that every file of any type will be passed through this stream. Make sure any transform stream will passthrough the files it doesn't support. Tools like gulp-if or gulp-filter will help filter invalid types and pass them through."

There is no further documentation or examples and the following gives an error of `TypeError: object is not a function`:

```
var gulpFilter = require('gulp-filter');

...

var beautifyFilter = gulpFilter([
  '_package.json'
]);

this.registerTransformStream(beautifyFilter(beautify({
  indentSize: 2,
  indentChar : ' ',
  preserveNewlines : false
})));
```

**Comment by sindresorhus** [comment]
You're opening this in the wrong place. This is for Yeoman to document.
