### ISSUE TITLE
Matching problem on Windows

### ISSUE THREAD

**Issue by kparkov** [sindresorhus/gulp-filter#52]
Some filters are not working on Windows.

This works:

```javascript
var scssfilter = filter(["**/*.scss"], { restore: true });
```

But this does not (everything is filtered out):

```javascript
var scssfilter = filter(["Components/**/*.scss"], { restore: true });
```

It seems anything more advanced is not working. This does not work either:

```javascript
var scssfilter = filter(["*", "!**/*.scss"], { restore: true });
```

It works with other libs utilizing minimatch, such as gulp.src.

**Comment by kparkov** [comment]
I should add that I am not aware whether this is a Windows-exclusive problem. It's just the platform I encountered the error on.

**Comment by LouisTakePILLz** [comment]
I'm experiencing the same issue here, albeit under a Linux environment. This is definitely not a Windows-exclusive issue and should be renamed accordingly.

**Comment by LouisTakePILLz** [comment]
@kparkov, see my issue report; you most likely forgot to set the base directory.

**Comment by kparkov** [comment]
@LouisTakePILLz, I agree, setting the base directory seems to solve the problem. I am closing this issue.
