### ISSUE TITLE
Does not seems to work with node 5.10

### ISSUE THREAD

**Issue by no-more** [sindresorhus/gulp-filter#63]
Hi,

I have just updated to node v5.10.1 and gulp-filter always return empty.

Is it only me?

Thanks.

**Comment by nfroidure** [comment]
Let's wait the build and see https://github.com/sindresorhus/gulp-filter/pull/64

**Comment by sindresorhus** [comment]
Tests pass https://travis-ci.org/sindresorhus/gulp-filter/builds/121436615.
