### ISSUE TITLE
Not working with gulp-git

### ISSUE THREAD

**Issue by Hanterdro** [sindresorhus/gulp-filter#69]
const f = filter(['!*.min.js']);

	return gulp.src(src)
		.pipe(f)
		.pipe(git.rm({args: '-f'}));

--->

	Error: Command failed: git rm  -f

If I remove the filter gulp-filter it is working like a charme.

Somehow gulp-git is no longer getting path informations when gulp-filter is used.

**Comment by sindresorhus** [comment]
You're probably using an incorrect glob pattern. Use gulp-debug to see what files matches your pattern.
