### ISSUE TITLE
Matching parent paths

### ISSUE THREAD

**Issue by stefanKuijers** [sindresorhus/gulp-filter#74]
Thanks for the handy plugin.

I ran into the following problem while running my gulp task for a different directory than my workin directory:

filter: ```'**/*.js'```
did not match: ```..\..\path\to\script.js```

To me this really seems to unexpected behavior.
I am aware of [this issue](https://github.com/sindresorhus/gulp-filter/issues/67).

My question is: 
is there any chance to merge in the snippet @cb1kenobi posted? It would be great if I don't have to fork and publish my own package for this.

Thanks in advance

**Comment by baihech** [comment]
me too！

**Comment by htko89** [comment]
Is this project abandoned?

**Comment by stefanKuijers** [comment]
Ping: @sindresorhus

**Comment by nfroidure** [comment]
I do no see any PR for that, has it been closed?

**Comment by cb1kenobi** [comment]
@nfroidure @stefanKuijers PR submitted!

**Comment by stefanKuijers** [comment]
@cb1kenobi Awesome!

**Comment by stefanKuijers** [comment]
@sindresorhus : Thanks!
