### ISSUE TITLE
Version 5.0.0 Changelog

### ISSUE THREAD

**Issue by simonepri** [sindresorhus/gulp-filter#79]
Could you provide more info about the version 5.0.0?
Also could you write something into the README about that problem?
https://github.com/sindresorhus/gulp-filter/issues/67
Something like:
"if you are upgrading from 3.0.1 you need to bla bla bla"

Thanks

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/gulp-filter/releases/tag/v5.0.0
